### ISSUE TITLE
您好，我想求一下前端监控部分的源码可以么。有个formatTime.js我找不到了，谢谢哥

### ISSUE THREAD

**Issue by Lemonadeccc** [lzq-dingyuan/zhufengongkaike#7]

**Comment by lzq-dingyuan** [comment]
刚刚我找了下，没有找到。。时间太久了
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Zhang ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年4月8日 18:18
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [lzq-dingyuan/zhufengongkaike] 您好，我想求一下前端监控部分的源码可以么。有个formatTime.js我找不到了，谢谢哥 (Issue #7)

**Comment by Lemonadeccc** [comment]
谢谢哥，我自己补上了缺的部分，生活愉快，工作顺利
